name = "nwlblog"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "BLOG_KV"
id = "60191bbc20b545e485e505bee54d8c8f"
preview_id = "9dea4140edeb49208ef3c0f9c79cfa63"

[vars]
ENVIRONMENT = "production"
RESEND_API_KEY = "re_PrsUWTuF_H7x54o3urdiCqHQ9x8vAtpaC"
GITHUB_CLIENT_ID = "Ov23li2JWD53KFj3jk9L"
GITHUB_CLIENT_SECRET = "6c208d446a8ed961482c6089db70e5c996696713"
SITE_URL = "https://blog.nwely.top"
WORKER_URL = "https://worker.blog.nwely.top"
FROM_EMAIL = "no-reply@nwely.top"
OLDCHAT_API_BASE = "http://60.205.94.101:8080"

[triggers]
crons = ["0 0 * * *"]